spring:
  application:
  name: eureka-demo-bluemix
server:
  port: 8761
eureka:
  instance:
  hostname: ${vcap.application.uris[0]:localhost}
client:
  registerWithEureka: false
  fetchRegistry: false
server:
  waitTimeInMsWhenSyncEmpty: 0
  serviceUrl:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
 logging:
  level:
  com.netflix: 'WARN'
  org.springframework.cloud: 'WARN'
    
    
    


    
